/**
 * Create By lnden on 2018/4/20
 */
const ADD_ITEMNUM = 'ADD_ITEMNUM';
const REMBER_ANSWER = 'REMBER_ANSWER';
const DELETE_ANSWER = 'DELETE_ANSWER';
const INITIALIZE_DATA = 'INITIALIZE_DATA';

export {
    ADD_ITEMNUM,
    REMBER_ANSWER,
    DELETE_ANSWER,
    INITIALIZE_DATA
}